AWSTemplateFormatVersion: 2010-09-09
Description: This will create an EC2 instance and the associated security group.

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: udacityProject
      ImageId: 'ami-0279c3b3186e54acd'
      InstanceType: t3.micro
      SecurityGroups:
        - !Ref InstanceSecurityGroup